apiVersion: v1
kind: ConfigMap
metadata:
  name: oes-autopilot
data:
  providerConfig: |
    application: isdapp
    lifetimeMinutes: 4
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "opsmx-argo,.*{{env.STABLE_POD_HASH}}.*,oes"
      canaryMetricScope: "opsmx-argo,.*{{env.LATEST_POD_HASH}}.*,oes"
      metricTemplateName: "prometheus-health-validator"
      serviceName: oes-autopilot
